#!/usr/bin/env python3
"""
Check data directory setup and provide guidance on expected structure.
"""

import sys
from pathlib import Path

# Add parent directory to path to import config
sys.path.insert(0, str(Path(__file__).parent.parent))

from config import DATA_ROOT


def check_dataset(dataset_name, dataset_path):
    """Check if a dataset directory is properly set up."""
    print(f"\n{dataset_name}:")
    print(f"  Path: {dataset_path}")
    
    if not dataset_path.exists():
        print("  Status: ✗ Not found")
        return False
    
    raw_dir = dataset_path / "raw"
    processed_dir = dataset_path / "processed"
    
    has_raw = raw_dir.exists()
    has_processed = processed_dir.exists()
    
    if has_raw:
        raw_files = list(raw_dir.iterdir())
        print(f"  Raw: ✓ {len(raw_files)} files/dirs")
        
        # Check for specific expected subdirectories
        if "pdbbind" in dataset_name.lower():
            refined_set = raw_dir / "refined-set"
            other_pl = raw_dir / "v2020-other-PL"
            if refined_set.exists():
                print(f"    - refined-set: ✓")
            else:
                print(f"    - refined-set: ✗ missing")
            if other_pl.exists():
                print(f"    - v2020-other-PL: ✓")
            else:
                print(f"    - v2020-other-PL: ✗ missing")
        elif "crossdocked" in dataset_name.lower():
            tar_file = raw_dir / "crossdocked_pocket10.tar.gz"
            split_file = raw_dir / "split_by_name.pt"
            if tar_file.exists():
                print(f"    - crossdocked_pocket10.tar.gz: ✓")
            else:
                print(f"    - crossdocked_pocket10.tar.gz: ✗ missing")
            if split_file.exists():
                print(f"    - split_by_name.pt: ✓")
            else:
                print(f"    - split_by_name.pt: ✗ missing")
    else:
        print("  Raw: ✗ Not found")
    
    if has_processed:
        processed_files = list(processed_dir.glob("*.pt"))
        print(f"  Processed: ✓ {len(processed_files)} .pt files")
    else:
        print("  Processed: ✗ Not created yet")
    
    return has_raw or has_processed


def main():
    print("=" * 70)
    print("Data Setup Checker")
    print("=" * 70)
    print(f"\nData Root: {DATA_ROOT}")
    print(f"Exists: {'✓ Yes' if DATA_ROOT.exists() else '✗ No'}")
    
    if not DATA_ROOT.exists():
        print("\n⚠ Warning: Data root directory does not exist!")
        print(f"Please create: {DATA_ROOT}")
        return 1
    
    # Check common dataset configurations
    datasets = [
        "pdbbind_filtered",
        "pdbbind_filtered_full",
        "pdbbind",
        "crossdocked_filtered",
        "crossdocked_filtered_full",
        "crossdocked",
    ]
    
    print("\n" + "=" * 70)
    print("Checking Dataset Directories")
    print("=" * 70)
    
    found_any = False
    for dataset in datasets:
        dataset_path = DATA_ROOT / dataset
        if check_dataset(dataset, dataset_path):
            found_any = True
    
    if not found_any:
        print("\n⚠ No datasets found in data root directory")
    
    # Provide guidance
    print("\n" + "=" * 70)
    print("Expected Directory Structure")
    print("=" * 70)
    print(f"""
{DATA_ROOT}/
├── pdbbind_filtered/
│   ├── raw/              # Place raw PDBBind data here
│   │   ├── refined-set/  # PDBbind refined set
│   │   ├── v2020-other-PL/  # PDBbind other set
│   │   └── index/        # Index files (if applicable)
│   └── processed/        # Generated by create_dataset.py
│
├── crossdocked_filtered/
│   ├── raw/              # Place raw CrossDocked data here
│   │   ├── crossdocked_pocket10.tar.gz
│   │   └── split_by_name.pt
│   └── processed/        # Generated by create_dataset.py
│
└── [other_datasets]/
    """)
    
    print("\n" + "=" * 70)
    print("Next Steps")
    print("=" * 70)
    print("""
1. Place raw dataset files in the appropriate raw/ directories
   
   For PDBBind:
   - Download from http://www.pdbbind.org.cn/
   - Extract refined-set and v2020-other-PL folders
   - Place in: {DATA_ROOT}/pdbbind_filtered/raw/
   - Expected structure:
     {DATA_ROOT}/pdbbind_filtered/raw/refined-set/
     {DATA_ROOT}/pdbbind_filtered/raw/v2020-other-PL/
   
   For CrossDocked:
   - Download from https://github.com/pengxingang/Pocket2Mol
   - Place crossdocked_pocket10.tar.gz and split_by_name.pt
   - In: {DATA_ROOT}/crossdocked_filtered/raw/

2. Run dataset creation script:
   python create_dataset.py pdbbind_filtered
   # or
   python create_dataset.py crossdocked_filtered

3. Verify processed files were created successfully
    """.replace("{DATA_ROOT}", str(DATA_ROOT)))
    
    print("\n" + "=" * 70)
    print("Environment Configuration")
    print("=" * 70)
    print(f"""
Current DATA_ROOT: {DATA_ROOT}

To change data location, either:
1. Set environment variable:
   export DIFFUSION_HOPPING_DATA_ROOT="/your/path/to/data"

2. Or edit config.py and change DEFAULT_DATA_ROOT

3. Or use --data-root argument with create_dataset.py:
   python create_dataset.py pdbbind_filtered --data-root /your/path
    """)
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
